### ISSUE TITLE
Bug in R update with regular expression

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy-package#114]
It turns out that your packages, during their tests, pass invalid
characters to regular expression operations. Invalid character here
means a sequence of bytes that doesn't match a character in the encoding
the string should have. Therefore, the regular expression operations may
not (and in some cases can not) proceed correctly.

Until now, R used to silently escape such invalid characters using
"<NN>", where NN is a hexadecimal number, but then the results of such
operations could be not quite as intended. R-devel has been improved to
detect these cases and report an error or warning, and this triggers
during package checks of your packages, so they will now start failing
their tests to signal the error.

More information is available in a blog post:

https://developer.r-project.org/Blog/public/2022/06/27/why-to-avoid-%5Cx-in-regular-expressions/index.html

even though in your cases (almost all) it seems to me following a quick
check that the invalid string is not the regular expression itself, but
one of the inputs.

Please fix your packages to ensure that the strings are valid. Very
likely often the problem is that the data you process are not properly
read into R - not converted to the current encoding (or to UTF-8); they
are expected to be in the current encoding, then, but they are not (the
current encoding may be different on different systems, though UTF-8 is
most common with recent R on recent systems). I've seen this happen also
in cases when the data were assumed to be ASCII, but in fact contained
some extended ASCII characters.

**Comment by zsteinmetz** [comment]
Thanks, Win!

This may be related to https://github.com/r-hyperspec/hyperSpec/pull/81. I'll try to fix it by specifying the encoding passed to hyperSpec.

**Comment by wincowgerDEV** [comment]
Nice find on that! You're a wizard.
