### ISSUE TITLE
[Bug]: An error has occurred. Check your logs or contact the app author for clarification.

### ISSUE THREAD

**Issue by nletwin97** [wincowgerDEV/OpenSpecy-package#130]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

3.5.1

### Platform and OS Version

macOS 10.15.1

### What happened?

When uploading a CSV file this is the error that pops up. Past CSV files that have already been uploaded to the system work but any new ones give me this error. 

### Steps to reproduce

1. upload csv
2.
3.
...

### Expected behavior

not this error message

**Comment by zsteinmetz** [comment]
Dear @nletwin97, thanks for letting us know. Could you please upload the CSV file in question here or, if confidential, truncate the data while keeping the files overall structure untouched? Also, do you run Open Specy locally or via https://openanalysis.org/openspecy/?

**Comment by wincowgerDEV** [comment]
I think we have this resolved now, got better error handling and file reading.
