### ISSUE TITLE
[Feature]: add ctb

### ISSUE THREAD

**Issue by philipp-baumann** [wincowgerDEV/OpenSpecy-package#144]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

person(given = "Philipp",
             family = "Baumann",
             email = "info@spectral-cockpit.space",
             role = c("ctb"),
             comment = c(ORCID = "0000-0002-3194-8975")),

### Problem

- there is no problem

### Proposed Solution

you can add me as ctb :-) cheers

### Alternatives Considered

no

**Comment by zsteinmetz** [comment]
Sounds sensible to me! Yet, if you plan to submit your package to CRAN anytime soon, it might be better if we just import your package rather than forking some of your functions. This would also simplify downstream maintenance in the long run. In case submitting to CRAN is not an option for you, feel free to submit a PR here if you like your code change/improved.

**Comment by philipp-baumann** [comment]
I suggest you keep the copy of the function like this. I plan to submit https://github.com/spectral-cockpit/opusreader2 to CRAN only, since the heurististics used in the succcessor is not bullet proof. But let's discuss about integrating opusreader2 😎

**Comment by philipp-baumann** [comment]
you may want to add Pierre Roudier, too @pierreroudier

**Comment by philipp-baumann** [comment]
agree about CRAN, valid point! Let's maybe discuss in person, we can also have a call since we are on the way to anyway submit opusreader2 to CRAN, and also we have some neat downstream utilities regarding workflow and metadata management. Currently, I am checking out some funding to allow me to work on it, be it either private labs or larger research collaborations. :-)

**Comment by zsteinmetz** [comment]
Great! Let's keep the fork then until opusreader2 is on CRAN. Let me know if I can help with anything. Should we arrange a call date via email? @wincowgerDEV would you like to join?

**Comment by wincowgerDEV** [comment]
Would love to join! Next week Wednesday onward is best for me.

**Comment by wincowgerDEV** [comment]
@philipp-baumann and @pierreroudier, got you added to the contributors now, you'll be listed on the next release.
