### ISSUE TITLE
[Bug]: heatmap_spec(showlegend=TRUE)

### ISSUE THREAD

**Issue by valentinavan** [wincowgerDEV/OpenSpecy-package#145]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Platform and OS Version

macOS 12.6.8 

### What happened?

Hi,

I was trying to show the legend within the heatmap function using showlegend=TRUE but it does not show it. 

Thanks

### Steps to reproduce

1. heatmap_spec(spectral_map_p, sn = spectral_map_p$metadata$sig_noise, min_sn = 5, font = list(color = "#000000"), showlegend = TRUE, colorscale = "Blues", reversescale = TRUE, paper_bgcolor = "white") 
2. 
3.
...

### Expected behavior

To show the legend

**Comment by zsteinmetz** [comment]
`showlegend` is currently not passed from `heatmap_spec()` to plotly. Should we add this feature, @wincowgerDEV?

**Comment by valentinavan** [comment]
Yes please, if you could also add more palettes it would be nice too. Thanks!

**Comment by wincowgerDEV** [comment]
I think we can add support for it as an option. I originally removed it because the legend wasn't working well with the app but I bet it could work on their now too, just never brought it back.

**Comment by wincowgerDEV** [comment]
Got this added to the latest PR @valentinavan. Should be up on CRAN in the next couple of weeks.
