### ISSUE TITLE
[Bug]: Missing Polymer.Category details for some library entries.

### ISSUE THREAD

**Issue by GCov** [wincowgerDEV/OpenSpecy-package#146]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

1.0.3

### What happened?

I was using the shiny app web interface to do some test matching with multiple spectra. After downloading the top matches and summarizing the results by 'Polymer.Category' I noticed that there were many NA values for plastic materials which should be categorized. This seems to be specifically occurring for the library from Cabernard et al. 2018 for PET (library ID 284264271bb8a760284d37bdc951e0a3). It could be an issue with text matching, as the SpectrumIdentity is listed as "Polyethyleneterephtalate" (maybe it's because there are no spaces). Unless the categories were assigned manually.

### Steps to reproduce

1. Upload spectra
2. Run matching (assuming PET is present)
3. Download top matches

### Expected behavior

Expected Polymer.Category to be polyester.

**Comment by wincowgerDEV** [comment]
Hey @GCov, thanks for this comment! In most cases, polymer_class should be used. There is a hierarchical relationship between plastic_or_not > polymer_class > Polymer.Category. The idea with these was that some people want to just know if something is plastic or not, some people want to know if something is a general group of polymers (also non polymers are here), and some want to know how detailed we can go. Unfortunately in many cases we couldn't find a more detailed name than the polymer_class that made sense. I think that your polyester category should be in the polymer_class column but if it isn't let me know.

**Comment by GCov** [comment]
Thanks very much @wincowgerDEV ! This makes sense. I hadn't looked var enough down the list of column names to see polymer_class. You're right and the categorization I was looking for is there.
