### ISSUE TITLE
[Bug]: XY coordinates flipped in maps

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy-package#150]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

current

### Platform and OS Version

Windows

### What happened?

The xy coordinates are flipped for me when I use read_any on my Thermo iN10 compared to what I see on the device. I am not sure if this is a cross platform issue or a platform specific issue so I am currently just posting this to see if other people are also having the bug and if they are we can easily swap them. 

### Steps to reproduce

1. Look at x y on hyperspectral imager during the acquisition and compare to the xy with read any and plotting with heatmap_spec

### Expected behavior

Same xy coordinates.

**Comment by zsteinmetz** [comment]
Which file type is this, ENVI? This may have occurred when we switched from hyperspec to caTools. I can look into it.

**Comment by wincowgerDEV** [comment]
Yeah it's for the envi files from a thermo in10. The CA_tiny_map extdata
should be a good test for this behavior.
