### ISSUE TITLE
[Feature]: Supporting TSV files

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy-package#153]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

Wesley Williams shared this .tsv file that is provided by the instrument he uses. Isn't currently supported but probably wouldn't be too hard since the extension is unique and its a text based file format. 

https://drive.google.com/file/d/16RkEX4xms1QV-FHv90Rag1szULo_j9Uv/view?usp=sharing

### Problem

tsv files not currently supported. 

### Proposed Solution

Create a read_tsv option and add to read_any. 

### Alternatives Considered

require they convert using another software.

**Comment by wincowgerDEV** [comment]
Also may want to add this file to the ext files for testing.

**Comment by zsteinmetz** [comment]
The OpenSpecy package already reads .tsv files with `read_text()`. No need for a separate function. We just need to add the file extension to `read_any()`.

**Comment by wincowgerDEV** [comment]
Oh awesome! Sounds like an easy fix.
