### ISSUE TITLE
[Feature]: Support for arbitrary TSV files

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy-package#175]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

Some software produce xy headers for their csv/tsv files. I want to support these. Wesley Williams has shared a matlab code for converting the tsv into the Open Specy format that could support this work. 

### Problem

common text files not supported. 

### Proposed Solution

add xy column name support (x is wavenumber, y is intensity). 

Attached is the spectrum and matlab code. 

[Background 10-12-2023 2-43 PM (GMT-04-00) (1).zip](https://github.com/user-attachments/files/16458604/Background.10-12-2023.2-43.PM.GMT-04-00.1.zip)

### Alternatives Considered

external export.

**Comment by zsteinmetz** [comment]
Hey @wincowgerDEV, thanks for sharing this. Huh, doesn't OpenSpecy support this already? `fread` should read text files no matter if its tab or comma separated values, shouldn't it? Or is it about the mere support of the TSV file ending?

**Comment by wincowgerDEV** [comment]
Good catch @zsteinmetz , looks like read_any already supports this. Turns out that shiny app just didn't allow the tsv and was throwing the error, just pushed a fix. https://github.com/wincowgerDEV/OpenSpecy-shiny/commit/96799924088c0e9da1445dd907f5b3593a50050e
