### ISSUE TITLE
[Feature]: Running into file size issues for maps

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy-package#176]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

Many spectral maps are around 10 GB in size in their envi format. We can read these files in with the CA tools functions fine (< 1min) but the transformation to an Open Specy object takes a considerable amount of time (>10 min). I think there has to be some more efficient strategies we can test here, perhaps performing the opperations on the arrays themselves and then transforming to a data.table object without doing as.data.table and doing something more clever to get the array into the data.table format that we need than dcasting. Reading in the file also takes up about 50 GB of Ram during the transformations and its uncompressed array is about 10 GB so there is about a 5X inflation going on somewhere during processing. I can share these test files if interested. 

### Problem

Big files take too long and aren't conserving compression very well. 

### Proposed Solution

Write the transformations more efficiently, perhaps consider some data compression options for these files too. 

### Alternatives Considered

Chunking the analysis could work too but I would rather first figure out a way to read these files onto Ram as it will be a lot faster that way.

**Comment by GCov** [comment]
Currently I'm getting an error that the file size is too big when uploading a ~10 MB .zip of map spectra to the shiny app.

**Comment by wincowgerDEV** [comment]
Thanks @GCov! Can you share the zip file here? I can try to debug!

**Comment by GCov** [comment]
[20241113_Sample1_NoKOH_Subsample2_1_spectra.zip](https://github.com/user-attachments/files/17781359/20241113_Sample1_NoKOH_Subsample2_1_spectra.zip)

Here it is, thank you!!
