### ISSUE TITLE
[Bug]: Load_lib

### ISSUE THREAD

**Issue by MPresearcher** [wincowgerDEV/OpenSpecy-package#178]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

3.0.0

### Platform and OS Version

macOS 12.7.6

### What happened?

I am new to R and trying to turn on identification for openspecy. When I run_app and turn on identification it says I need to get_lib("Derivative") When I go to R and try to download the spectral library via get_lib it says it has downloaded, I then code for load_lib and it tells me I need get_lib, this is what it looks like. Please help I feel like I am going in circles. 

> get_lib(type = "derivative")
Fetching Open Specy reference libraries from OSF ...
Fetching derivative library...
trying URL 'https://osf.io/download/2qbkt/'
Content type 'application/octet-stream' length 148873183 bytes (142.0 MB)
==================================================
downloaded 142.0 MB

Use 'load_lib()' to load the library
> lib <- load_lib(type = "derivative")
Error: Library missing or incomplete: derivative; use 'get_lib()' to download a current version

### Steps to reproduce

1.
2.
3.
...> get_lib(type = "derivative")
Fetching Open Specy reference libraries from OSF ...
Fetching derivative library...
trying URL 'https://osf.io/download/2qbkt/'
Content type 'application/octet-stream' length 148873183 bytes (142.0 MB)
==================================================
downloaded 142.0 MB

Use 'load_lib()' to load the library
> lib <- load_lib(type = "derivative")

### Expected behavior

I should be able to load the library to turn on identification for openspecy

**Comment by wincowgerDEV** [comment]
@MPresearcher , sorry for missing this. I think this issue is related to a bug with MAC computers that we recently fixed. Could you install the latest package and try again and let us know if the issue persists?
