### ISSUE TITLE
add support for commercial library file download

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy-package#69]
A request came in to support .idb or .idt formats for downloading the Open Specy spectral library.

**Comment by zsteinmetz** [comment]
Is there any documentation about those formats?

**Comment by wincowgerDEV** [comment]
Sorry late to reply here, don't know how I missed this. I think we should just close this for now. Been over a year and don't really have much motivation to improve the access from open specy -> commercial software unless the commercial labs are willing to participate and fund. Much more interest to move data the opposite direction.
