### ISSUE TITLE
Add cluster levels as an option to matching

### ISSUE THREAD

**Issue by wincowgerDEV** [wincowgerDEV/OpenSpecy-package#95]
Shreyas did cluster analysis on the FTIR Open Specy database. We should add an option to search based on the cluster group (which simplifies analysis), in the future it would be useful to use this when developing AI by conducting feature extraction using his standard deviation analysis and classifying the clusters instead of the classes currently in the list, his notes are below:

In short, I used SciPy’s hierarchical clustering and set threshold to cluster spectra together if (pearson_coefficient > 0.3). With this criterion, the data neatly separates into 33 clusters. To make this more useful:

I’ve created a figure (simplified_cluster_grid.png) attached that shows mean and standard deviation of all spectra contained respectively within each cluster – to me this boosts some confidence in the reliability of this process.
The original OpenSpecy web download includes a metadata file. The clustering code adds a column to this file (see final column called “cluster_ix” in the file ftir_metadata_clusters.csv attached)
Up till here everything is machine/code processed. But as a final step, I use human judgement in the attached file cluster_keys_simplified.csv where I added the last column “simplified_cluster_name” to enter simplified polymer category names similar to Primpke 2018.
 
I’m incorporating these into our lab’s analysis code – hopefully some of our data going forward will be labelled using these simplified cluster names after fitting with the OpenSpecy database. I also think this clustering and the simplified category names could be useful to other OpenSpecy users. All of this is now available on [GitHub](https://github.com/Ocean-Wise/OpenSpecy_data_sorting) (with a more descriptive [readme file](https://github.com/Ocean-Wise/OpenSpecy_data_sorting/blob/main/README.md) and step-by-step [jupyter notebook](https://github.com/Ocean-Wise/OpenSpecy_data_sorting/blob/main/nb_data_clustering.ipynb)). 

[ftir_metadata_clusters.csv](https://github.com/wincowgerDEV/OpenSpecy/files/7008872/ftir_metadata_clusters.csv)
[cluster_keys_simplified.csv](https://github.com/wincowgerDEV/OpenSpecy/files/7008873/cluster_keys_simplified.csv)
![simplified_cluster_grid](https://user-images.githubusercontent.com/26821843/129939560-2c563fe0-f82a-4b24-8904-1a4d65691507.png)

**Comment by Shreyas-Patankar** [comment]
to add some more context, this process is based on the guidelines in Primpke et al., 2018 and is motivated by the fact that FTIR spectra from different materials can sometimes be very similar and not distinguishable due to instrument limitations.

**Comment by wincowgerDEV** [comment]
This is actually built in now with the mediod clustered library.
